// List of themes to be ranked
const themes = [
    { name: "Dark Souls series", max_score: 40 },
    { name: "Xenoblade Chronicles", max_score: 40 },
    { name: "The Legend of Zelda series", max_score: 50 },
    { name: "Star Wars lore", max_score: 70 },
    { name: "Dungeons & Dragons", max_score: 80 },
    { name: "Warhammer 40,000", max_score: 80 },
    { name: "Final Fantasy series", max_score: 70 },
    { name: "Star Trek universe", max_score: 60 },
    { name: "Marvel Comics", max_score: 80 },
    { name: "DC Comics", max_score: 80 },
    { name: "Pokémon games", max_score: 20 },
    { name: "Magic: The Gathering", max_score: 60 },
    { name: "Lord of the Rings lore", max_score: 70 },
    { name: "Harry Potter series", max_score: 50 },
    { name: "Doctor Who", max_score: 60 },
    { name: "Battlestar Galactica", max_score: 40 },
    { name: "StarCraft", max_score: 50 },
    { name: "World of Warcraft", max_score: 90 },
    { name: "Assassin's Creed series", max_score: 60 },
    { name: "Halo series", max_score: 50 },
    { name: "Mass Effect series", max_score: 60 },
    { name: "Elder Scrolls series", max_score: 80 },
    { name: "Firefly (TV series)", max_score: 30 },
    { name: "Cosplay", max_score: 40 },
    { name: "Tabletop RPGs", max_score: 70 },
    { name: "Retro video games (e.g., NES, SNES)", max_score: 50 },
    { name: "Anime (e.g., Naruto, One Piece)", max_score: 80 },
    { name: "Manga (e.g., Attack on Titan)", max_score: 80 },
    { name: "Comic book conventions", max_score: 30 },
    { name: "Fantasy novels", max_score: 70 },
    { name: "Science fiction novels", max_score: 70 },
    { name: "Cyberpunk genre", max_score: 60 },
    { name: "Steampunk genre", max_score: 60 },
    { name: "Space exploration facts", max_score: 90 },
    { name: "Quantum physics", max_score: 90 },
    { name: "Astrophysics", max_score: 90 },
    { name: "Robotics", max_score: 60 },
    { name: "Artificial intelligence", max_score: 60 },
    { name: "Biotechnology", max_score: 60 },
    { name: "Genetics", max_score: 60 },
    { name: "Meteorology", max_score: 60 },
    { name: "Plate tectonics", max_score: 60 },
    { name: "Oceanography", max_score: 60 },
    { name: "Paleontology", max_score: 60 },
    { name: "Archaeology", max_score: 60 },
    { name: "Ancient civilizations", max_score: 80 },
    { name: "Mythology (Greek, Roman, Norse)", max_score: 70 },
    { name: "Dinosaurs", max_score: 40 },
    { name: "Cryptozoology", max_score: 30 },
    { name: "Cryptography", max_score: 60 },
    { name: "Astronomy", max_score: 80 },
    { name: "Stargazing", max_score: 30 },
    { name: "Constellations", max_score: 30 },
    { name: "Planetary science", max_score: 60 },
    { name: "Black holes", max_score: 90 },
    { name: "Dark matter", max_score: 90 },
    { name: "Parallel universes", max_score: 90 },
    { name: "Time travel theories", max_score: 60 },
    { name: "Historical reenactments", max_score: 30 },
    { name: "Medieval history", max_score: 50 },
    { name: "Renaissance fairs", max_score: 30 },
    { name: "Historical documentaries", max_score: 90 },
    { name: "Geographic landmarks", max_score: 50 },
    { name: "World capitals", max_score: 30 },
    { name: "Famous explorers", max_score: 30 },
    { name: "Mount Everest", max_score: 30 },
    { name: "The Mariana Trench", max_score: 30 },
    { name: "The Great Barrier Reef", max_score: 30 },
    { name: "The Amazon Rainforest", max_score: 30 },
    { name: "The Seven Wonders of the World", max_score: 50 },
    { name: "Geological formations", max_score: 50 },
    { name: "Volcanology", max_score: 50 },
    { name: "Earth's magnetic field", max_score: 50 },
    { name: "Biomes", max_score: 30 },
    { name: "Ecosystems", max_score: 50 },
    { name: "Endangered species", max_score: 50 },
    { name: "Conservation efforts", max_score: 50 },
    { name: "Renewable energy", max_score: 50 },
    { name: "Space missions (e.g., Apollo, Mars rovers)", max_score: 90 },
    { name: "Science fairs", max_score: 30 },
    { name: "Robotics competitions", max_score: 30 },
    { name: "Science fiction movies", max_score: 80 },
    { name: "Fantasy movies", max_score: 80 },
    { name: "Comic book art", max_score: 50 },
    { name: "Concept art", max_score: 50 },
    { name: "3D modeling", max_score: 50 },
    { name: "Virtual reality", max_score: 80 },
    { name: "Augmented reality", max_score: 60 },
    { name: "Game development", max_score: 80 },
    { name: "Indie games", max_score: 60 },
    { name: "Speedrunning", max_score: 30 },
    { name: "Esports", max_score: 80 },
    { name: "Streaming on Twitch", max_score: 30 },
    { name: "Collecting action figures", max_score: 30 },
    { name: "Building model kits", max_score: 50 },
    { name: "Reading graphic novels", max_score: 50 },
    { name: "Writing fan fiction", max_score: 30 },
    { name: "Creating fan art", max_score: 50 },
    { name: "Science museums", max_score: 50 },
    { name: "Planetariums", max_score: 30 },
    { name: "Astronomical observatories", max_score: 50 },
    { name: "Participating in hackathons", max_score: 30 },
    { name: "Programming languages (e.g., Python, JavaScript)", max_score: 50 },
    { name: "Building computers", max_score: 50 },
    { name: "Internet culture", max_score: 30 },
    { name: "Memes", max_score: 30 },
    { name: "Online forums", max_score: 30 },
    { name: "Video game lore", max_score: 80 },
    { name: "Classic literature", max_score: 50 },
    { name: "Poetry (e.g., Edgar Allan Poe)", max_score: 50 },
    { name: "Shakespearean plays", max_score: 50 },
    { name: "Interactive fiction", max_score: 30 },
    { name: "Text-based adventure games", max_score: 30 },
    { name: "Live-action role-playing (LARP)", max_score: 50 },
    { name: "Game theory (Not MatPat)", max_score: 50 },
    { name: "Comic book movies", max_score: 80 },
    { name: "Graphic design", max_score: 50 },
    { name: "Animation (e.g., Studio Ghibli films)", max_score: 80 },
    { name: "Space operas", max_score: 50 },
    { name: "Cosplay craftsmanship", max_score: 50 },
    { name: "Sewing costumes", max_score: 30 },
    { name: "Prop making", max_score: 30 },
    { name: "LEGO building", max_score: 30 },
    { name: "Retro computing", max_score: 30 },
    { name: "Hacking and cybersecurity", max_score: 90 },
    { name: "Linux operating system", max_score: 50 },
    { name: "Web development", max_score: 80 },
    { name: "Database management", max_score: 50 },
    { name: "Artificial neural networks", max_score: 50 },
    { name: "Quantum computing", max_score: 90 },
    { name: "Space telescopes (e.g., Hubble, James Webb)", max_score: 50 },
    { name: "Meteor showers", max_score: 30 },
    { name: "Eclipses", max_score: 30 },
    { name: "Satellites and space stations", max_score: 50 },
    { name: "Mars colonization plans", max_score: 90 },
    { name: "Space tourism", max_score: 90 },
    { name: "Theoretical physics", max_score: 90 },
    { name: "Science fiction TV shows", max_score: 80 },
    { name: "Writing scripts and screenplays", max_score: 50 },
    { name: "Indie film production", max_score: 50 },
    { name: "Video editing", max_score: 50 },
    { name: "Digital photography", max_score: 50 },
    { name: "Astronomy clubs", max_score: 30 },
    { name: "Amateur radio", max_score: 30 },
    { name: "Drone piloting", max_score: 30 },
    { name: "RC cars and planes", max_score: 30 },
    { name: "Mechanical keyboards", max_score: 30 },
    { name: "DIY electronics", max_score: 50 },
    { name: "Arduino projects", max_score: 50 },
    { name: "Raspberry Pi projects", max_score: 50 },
    { name: "Building PCs", max_score: 50 },
    { name: "Collecting vintage technology", max_score: 30 },
    { name: "Data science", max_score: 90 },
    { name: "Machine learning", max_score: 90 },
    { name: "Natural language processing", max_score: 90 },
    { name: "Linguistics", max_score: 50 },
    { name: "Language learning", max_score: 90 },
    { name: "Translating ancient texts", max_score: 50 },
    { name: "Historical linguistics", max_score: 50 },
    { name: "Writing fantasy maps", max_score: 30 },
    { name: "Creating fictional worlds", max_score: 90 },
    { name: "Drawing comics", max_score: 50 },
    { name: "Producing podcasts", max_score: 50 },
    { name: "Streaming gameplay", max_score: 30 },
    { name: "Virtual meetups", max_score: 30 },
    { name: "Online communities (e.g., Reddit)", max_score: 50 },
    { name: "Creating mods for games", max_score: 50 },
    { name: "Participating in beta testing", max_score: 30 },
    { name: "Game theory analysis", max_score: 50 },
    { name: "Competitive programming", max_score: 50 },
    { name: "Participating in coding challenges", max_score: 30 },
    { name: "Digital art", max_score: 80 },
    { name: "3D printing", max_score: 50 },
    { name: "Creating YouTube content", max_score: 50 },
    { name: "Fitness apps and tracking", max_score: 30 },
    { name: "Biohacking", max_score: 30 },
    { name: "Collecting trading cards (e.g., Yu-Gi-Oh!, Pokémon)", max_score: 50 },
    { name: "Playing chess", max_score: 30 },
    { name: "Solving Rubik's Cubes", max_score: 30 },
    { name: "Magic tricks", max_score: 30 },
    { name: "Sudoku and puzzles", max_score: 30 },
    { name: "Fantasy sports leagues", max_score: 30 },
    { name: "Collecting stamps and coins", max_score: 30 },
    { name: "Collecting Funko Pops", max_score: 30 },
    { name: "Astronomy photography", max_score: 50 },
    { name: "Building model railroads", max_score: 50 },
    { name: "Learning to play musical instruments", max_score: 50 },
    { name: "Synthesizers and electronic music", max_score: 50 },
    { name: "Exploring virtual worlds (e.g., Second Life)", max_score: 50 },
    { name: "Analyzing TV show theories", max_score: 50 },
    { name: "Writing speculative fiction", max_score: 80 },
    { name: "Designing board games", max_score: 50 },
    { name: "Solving mysteries and escape rooms", max_score: 50 },
    { name: "Historical board games (e.g., Risk)", max_score: 50 },
    { name: "Attending tech expos", max_score: 50 },
    { name: "Virtual reality games", max_score: 80 },
    { name: "Augmented reality experiences", max_score: 80 },
    { name: "Creating virtual environments", max_score: 90 },
        { name: "Vocaloid community", max_score: 70 },
        { name: "K-Drama", max_score: 50 },
        { name: "Visual novels", max_score: 50 },
        { name: "Idols (e.g., BTS, EXO)", max_score: 60 },
        { name: "J-Pop", max_score: 50 },
        { name: "Eurobeat music", max_score: 50 },
        { name: "Skrillex and dubstep music", max_score: 50 },
        { name: "Retro arcade gaming", max_score: 60 },
        { name: "Lofi music", max_score: 50 },
        { name: "Techno and EDM music", max_score: 50 },
        { name: "The Walking Dead TV show", max_score: 40 },
        { name: "True crime enthusiasts", max_score: 50 },
        { name: "Tattoo culture", max_score: 30 },
        { name: "Piercing culture", max_score: 30 },
        { name: "Streetwear fashion", max_score: 30 },
        { name: "Sneakerhead culture", max_score: 30 },
        { name: "Indie music scene", max_score: 40 },
        { name: "Concert photography", max_score: 50 },
        { name: "Cosplay photography", max_score: 50 },
        { name: "Online streaming culture (Twitch, YouTube)", max_score: 40 },
        { name: "Cryptocurrency and NFTs", max_score: 70 },
        { name: "Video game modding", max_score: 70 },
        { name: "Fidget toy collecting", max_score: 30 },
        { name: "Paper crafts (origami, scrapbooking)", max_score: 40 },
        { name: "Calligraphy", max_score: 50 },
        { name: "Stamp collecting", max_score: 30 },
        { name: "Coin collecting", max_score: 30 },
        { name: "Pin collecting", max_score: 40 },
        { name: "Minecraft modding", max_score: 60 },
        { name: "Retro computer games", max_score: 50 },
        { name: "TTRPG (Tabletop Role-Playing Games) Dungeon Mastering", max_score: 70 },
        { name: "Roleplay (RP) in online communities", max_score: 40 },
        { name: "Game design and mechanics", max_score: 80 },
        { name: "VR games", max_score: 80 },
        { name: "Escape rooms (online and physical)", max_score: 40 },
        { name: "Board game strategy", max_score: 60 },
        { name: "Card games (e.g., Yu-Gi-Oh!, Magic: The Gathering)", max_score: 60 },
        { name: "Tabletop wargaming (e.g., Warhammer, X-Wing)", max_score: 70 },
        { name: "Dungeons & Dragons world-building", max_score: 80 },
        { name: "Geocaching", max_score: 40 },
        { name: "Cryptozoology", max_score: 50 },
        { name: "Horror", max_score: 50 },
        { name: "Classic horror literature (e.g., Edgar Allan Poe)", max_score: 50 },
        { name: "Gothic fashion", max_score: 40 },
        { name: "Vampire lore", max_score: 50 },
        { name: "Superhero movies", max_score: 60 },
        { name: "Indie film culture", max_score: 50 },
        { name: "Horror movie buffs", max_score: 50 },
        { name: "Folk music", max_score: 40 },
        { name: "Jazz music", max_score: 40 },
        { name: "Classical music", max_score: 40 },
        { name: "Heavy metal music", max_score: 50 },
        { name: "Hardcore punk music", max_score: 50 },
        { name: "Alternative music", max_score: 50 },
        { name: "Comedy (stand-up and improv)", max_score: 30 },
        { name: "Magic: The Gathering tournaments", max_score: 60 },
        { name: "Board game tournaments", max_score: 60 },
        { name: "Dungeons & Dragons online play (e.g., Roll20, Discord)", max_score: 70 },
        { name: "Rocket League (eSports)", max_score: 50 },
        { name: "Fortnite (competitive scene)", max_score: 60 },
        { name: "League of Legends lore", max_score: 70 },
        { name: "Competitive Overwatch", max_score: 60 },
        { name: "Minecraft survival servers", max_score: 60 },
        { name: "Speedrunning communities", max_score: 50 },
        { name: "Fanfiction writing", max_score: 50 },
        { name: "Fan art creation", max_score: 50 },
        { name: "Fandoms for specific video game franchises", max_score: 60 },
        { name: "Anime fan theories", max_score: 50 },
        { name: "Geek fashion", max_score: 40 },
        { name: "Twitch streaming (gaming and other content)", max_score: 40 },
        { name: "YouTube content creation", max_score: 50 },
        { name: "Collaborative storytelling", max_score: 50 },
        { name: "Mythical creature lore (dragons, griffins, etc.)", max_score: 60 },
        { name: "Fictional languages (e.g., Elvish, Klingon)", max_score: 60 },
        { name: "Fictional world-building (e.g., planets, societies)", max_score: 70 },
        { name: "Life simulation games (e.g., The Sims)", max_score: 50 },
        { name: "Building LEGO sets", max_score: 50 },
        { name: "Urban exploration (urbex)", max_score: 50 },
        { name: "Murder mystery games", max_score: 50 },
        { name: "Survivalist skills", max_score: 40 },
        { name: "Hacking culture", max_score: 70 },
        { name: "Online privacy and security", max_score: 60 },
        { name: "Digital art communities (e.g., DeviantArt, ArtStation)", max_score: 60 },
        { name: "Fictional worlds in literature (e.g., Narnia, Discworld)", max_score: 70 },
        { name: "Star Wars extended universe", max_score: 70 },
        { name: "Cinematography", max_score: 50 },
        { name: "Space opera fandom (e.g., Star Wars, Battlestar Galactica)", max_score: 70 },
        { name: "Astrobiology", max_score: 60 },
        { name: "Cyborg and transhumanism culture", max_score: 50 },
        { name: "Maker culture (DIY, Inventors, Hackers)", max_score: 60 },
        { name: "3D modeling and CAD software", max_score: 50 },
        { name: "Collecting pop culture memorabilia", max_score: 30 },
        { name: "Sculpting and clay modeling", max_score: 40 },
        { name: "Sewing and knitting (crafting)", max_score: 40 },
        { name: "Steampunk", max_score: 50 },
        { name: "Pirate culture", max_score: 40 },
        { name: "Philosophical thinking", max_score: 60 },
        { name: "Dystopian literature", max_score: 60 },
        { name: "Survival horror games", max_score: 60 },
        { name: "Post-apocalyptic games", max_score: 50 },
        { name: "Documentary films", max_score: 40 },
        { name: "Wrestling", max_score: 50 },
        { name: "Science fiction literature", max_score: 60 },
        { name: "Space exploration", max_score: 70 },
        { name: "Future technology", max_score: 60 },
        { name: "Artificial intelligence enthusiasts", max_score: 70 },
        { name: "Programming and coding culture", max_score: 80 },
        { name: "Internet of Things (IoT)", max_score: 60 },
        { name: "Quantum computing", max_score: 70 },
        { name: "Mobile app development", max_score: 60 },
        { name: "VR/AR technology", max_score: 80 },
        { name: "Science and tech expos", max_score: 60 },
        { name: "Astronomy", max_score: 70 },
        { name: "UFO sightings and alien theories", max_score: 60 },
        { name: "Hackathons", max_score: 50 },
        { name: "Biotechnology enthusiasts", max_score: 60 },
        { name: "Genetic engineering and CRISPR", max_score: 70 },
        { name: "Tech gadget enthusiasts", max_score: 60 },
        { name: "Cyberpunk", max_score: 70 },
        { name: "Robotics", max_score: 60 }
      ];
  


  const surveyForm = document.getElementById('survey-form');
  const resultContainer = document.getElementById('result');
  const totalScoreElement = document.getElementById('total-score');
  const submitButton = document.getElementById('submit-btn');
  
  // Calculate the highest possible score
  const highestPossibleScore = themes.reduce((total, theme) => total + theme.max_score, 0);
  
  // Create input fields dynamically for each theme
  themes.forEach(theme => {
    const themeDiv = document.createElement('div');
    themeDiv.classList.add('theme-item');
  
    const label = document.createElement('label');
    label.innerHTML = `${theme.name} (1 - ${theme.max_score})`;
  
    const input = document.createElement('input');
    input.type = 'number';
    input.min = 1;
    input.max = theme.max_score;
    input.value = 1;
    input.id = theme.name;
    input.classList.add('score-input');
  
    themeDiv.appendChild(label);
    themeDiv.appendChild(input);
    surveyForm.appendChild(themeDiv);
  });
  
  // Function to calculate total score
  function calculateTotalScore() {
    let totalScore = 0;
    themes.forEach(theme => {
      const input = document.getElementById(theme.name);
      totalScore += parseInt(input.value);
    });
    return totalScore;
  }
  
  // Handle submit button click
  submitButton.addEventListener('click', () => {
    const totalScore = calculateTotalScore();
    totalScoreElement.innerText = `Your total score is ${totalScore} / ${highestPossibleScore}`;
    resultContainer.style.display = 'block';
  });